--- 
services: 
  apigateway: 
    build: zuul-gatewayservice/
    depends_on: 
      - eurekaserver
    expose: 
      - 8095
    image: zuul-service
    network_mode: host
    ports: 
      - "8095:8095"
    restart: always
  eurekaserver: 
    build: eureka-server/
    expose: 
      - 8010
    image: "eureka-servcie:latest"
    network_mode: host
    ports: 
      - "8010:8010"
    restart: always
  mongo: 
    container_name: mongo_docker
    hostname: localhost
    image: "mongo:3.4-jessie"
    network_mode: host
    ports: 
      - "27017:27017"
    restart: always
    volumes: 
      - "./data/db:/data/db"
  music_app: 
    build: AppRegistration/
    container_name: appRegistration_docker
    depends_on: 
      - mongo
      - eureka
      - apigateway
    expose: 
      - 8088
    image: "appRegistration:latest"
    network_mode: host
    ports: 
      - "8088:8088"
    restart: always
version: "3"
volumes: 
  data: ~

