version: '2.1'
 
services: 
  apigateway: 
    build: zuul-gatewayservice/
    depends_on: 
      - eurekaserver
    image: zuul-service
    network_mode: host
    ports: 
      - 8095:8095
    restart: always
    healthcheck:
     test: "exit 0"

  eurekaserver: 
    build: eureka-server/
    image: eureka-servcie:latest
    network_mode: host
    ports: 
      - 8010:8010
    restart: always
    healthcheck:
     test: "exit 0"

  mongo: 
    container_name: mongo_docker
    hostname: localhost
    image: mongo:3.4-jessie
    network_mode: host
    ports: 
      - 27017:27017
    restart: always
    volumes: 
      - ./data/db:/data/db

  app-registration: 
    build: AppRegistration/
    container_name: appregistration_docker
    depends_on: 
      - mongo
      - eurekaserver
      - apigateway
    image: appregistration:latest
    network_mode: host
    ports: 
      - 8088:8088
    restart: always
    healthcheck:
     test: "exit 0"
volumes: 
  data: ~

