version: "2"
services:

  apigateway:
    image: zuul-service
    build: zuul-gatewayservice/
    restart: always
    network_mode: host
    depends_on:
    - eurekaserver
    ports:
    - 8095:8095
    expose:
    - 8095

  eurekaserver:
    image: eureka-servcie:latest
    build: eureka-server/
    restart: always
    network_mode: host
    ports:
    - 8010:8010
    expose:
    - 8010

  mongo:
   image: mongo:3.4-jessie
   ports:
   - 27017:27017
   container_name: mongo_docker
   restart: always
   network_mode: host
   hostname: localhost
   volumes:
   - ./data/db:/data/db


  music_app:
    image: appRegistration:latest
    build: appRegistration/
    container_name: appRegistration_docker
    restart: always
    network_mode: host
    depends_on:
    - mongo
    - eureka
    - apigateway
    ports:
    - 8088:8088
    expose:
    - 8088

 volumes:
  data:




