version: '2.1'
 
services: 
  apigateway: 
    build: zuul-gatewayservice/
    depends_on: 
      - eurekaserver
    image: zuul-service
    network_mode: host
    ports: 
      - 8095:8095
    restart: always
    healthcheck:
     test: "exit 0"

  eurekaserver: 
    build: eureka-server/
    image: eureka-servcie:latest
    network_mode: host
    ports: 
      - 8010:8010
    restart: always
    healthcheck:
     test: "exit 0"

  mongo: 
    container_name: mongo_docker
    hostname: localhost
    image: mongo:3.4-jessie
    network_mode: host
    ports: 
      - 27017:27017
    restart: always
    volumes: 
      - ./data/db:/data/db

  app-registration: 
    build: AppRegistration/
    container_name: appregistration_docker
    depends_on: 
      - mongo
      - eurekaserver
      - apigateway
    image: appregistration:latest
    network_mode: host
    ports: 
      - 8088:8088
    restart: always
    healthcheck:
     test: "exit 0"
     
  user-service:
   build: userservice/
   container_name: userservice_docker
   depends_on: 
      - mongo
      - eurekaserver
      - apigateway
   image: userservice:latest
   network_mode: host
   ports: 
     - 8096:8096
   restart: always
   healthcheck:
    test: "exit 0"
    
  data-collector:
   build: Data-Collector/
   container_name: datacollector_docker
   depends_on: 
      - kafka
      - eurekaserver
      - apigateway
   image: dockercollector:latest
   network_mode: host
   ports: 
     - 8001:8001
   restart: always
   healthcheck:
    test: "exit 0"
    
  kafkaservice:
   image: landoop/fast-data-dev
   container_name: kfka_docker
   restart: always
   network_mode: host
   hostname: localhost
   ports:
    - 2181:2181
    - 8030:8030
    - 8081:8081
    - 8084:8084
    - 8083:8083
    - 9092:9092
   environment:
    WEB_PORT: 8030
    REST_PORT: 8084
    BROKER_PORT: 9092
    ZK_PORT: 2181
    CONNECT_PORT: 8083
    REGISTRY_PORT: 8081
    ADV_HOST: localhost
   healthcheck:
    test: "exit 0"
   
volumes: 
  data: ~

